//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVOne.Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVOne.Tool.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not install plugin {0}.
        /// </summary>
        public static string ErrorCannotInstallPlugins {
            get {
                return ResourceManager.GetString("ErrorCannotInstallPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory is null or not exist..
        /// </summary>
        public static string ErrorDir {
            get {
                return ResourceManager.GetString("ErrorDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{}&apos; not exists..
        /// </summary>
        public static string ErrorDirectoryNotExists {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path &apos;{0}&apos; not exists..
        /// </summary>
        public static string ErrorPathNotExists {
            get {
                return ResourceManager.GetString("ErrorPathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to normal scenario.
        /// </summary>
        public static string ExamplesNormalScenario {
            get {
                return ResourceManager.GetString("ExamplesNormalScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add plugin repository..
        /// </summary>
        public static string HelpTextAddRepo {
            get {
                return ResourceManager.GetString("HelpTextAddRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection Type, could be PornMovie,default is PornMovie..
        /// </summary>
        public static string HelpTextCollectionType {
            get {
                return ResourceManager.GetString("HelpTextCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to use for the data folder (database files, etc.)..
        /// </summary>
        public static string HelpTextdatadir {
            get {
                return ResourceManager.GetString("HelpTextdatadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to scan..
        /// </summary>
        public static string HelpTextDirectory {
            get {
                return ResourceManager.GetString("HelpTextDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to external FFmpeg executable to use in place of default found in PATH..
        /// </summary>
        public static string HelpTextffmpeg {
            get {
                return ResourceManager.GetString("HelpTextffmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filename.
        /// </summary>
        public static string HelpTextFileName {
            get {
                return ResourceManager.GetString("HelpTextFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install plugin..
        /// </summary>
        public static string HelpTextInstallPlugin {
            get {
                return ResourceManager.GetString("HelpTextInstallPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all plugins in plugin repository..
        /// </summary>
        public static string HelpTextShowAvaliablePlugins {
            get {
                return ResourceManager.GetString("HelpTextShowAvaliablePlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all installed plugins..
        /// </summary>
        public static string HelpTextShowInstalledPlugins {
            get {
                return ResourceManager.GetString("HelpTextShowInstalledPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show plugin repository list..
        /// </summary>
        public static string HelpTextShowPluginRepositoryList {
            get {
                return ResourceManager.GetString("HelpTextShowPluginRepositoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print system info..
        /// </summary>
        public static string HelpTextVerbInfo {
            get {
                return ResourceManager.GetString("HelpTextVerbInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan &amp; organize files under specific folder. .
        /// </summary>
        public static string HelpTextVerbOrganize {
            get {
                return ResourceManager.GetString("HelpTextVerbOrganize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage plugins..
        /// </summary>
        public static string HelpTextVerbPlugin {
            get {
                return ResourceManager.GetString("HelpTextVerbPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage plugin repository..
        /// </summary>
        public static string HelpTextVerbPluginRepo {
            get {
                return ResourceManager.GetString("HelpTextVerbPluginRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print movie metadata by filename..
        /// </summary>
        public static string HelpTextVerbPrintMetadata {
            get {
                return ResourceManager.GetString("HelpTextVerbPrintMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan files under specific folder and preview the organize result..
        /// </summary>
        public static string HelpTextVerbScan {
            get {
                return ResourceManager.GetString("HelpTextVerbScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading and install plugin &apos;{0}&apos;.
        /// </summary>
        public static string InfoDownloadingPlugin {
            get {
                return ResourceManager.GetString("InfoDownloadingPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching plugin....
        /// </summary>
        public static string InfoSearchingPlugins {
            get {
                return ResourceManager.GetString("InfoSearchingPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path &apos;{0}&apos; not valid media file..
        /// </summary>
        public static string InvalidMoviePath {
            get {
                return ResourceManager.GetString("InvalidMoviePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Možnost &apos;{0}&apos; je definována ve špatném formátu..
        /// </summary>
        public static string SentenceBadFormatConversionErrorOption {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value not bound to option name is defined with a bad format..
        /// </summary>
        public static string SentenceBadFormatConversionErrorValue {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token &apos;{0}&apos; is not recognized..
        /// </summary>
        public static string SentenceBadFormatTokenError {
            get {
                return ResourceManager.GetString("SentenceBadFormatTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verb &apos;{0}&apos; is not recognized..
        /// </summary>
        public static string SentenceBadVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceBadVerbSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erros(S):.
        /// </summary>
        public static string SentenceErrorsHeadingText {
            get {
                return ResourceManager.GetString("SentenceErrorsHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display this help screen..
        /// </summary>
        public static string SentenceHelpCommandTextOption {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display more information on a specific command..
        /// </summary>
        public static string SentenceHelpCommandTextVerb {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one option in a group &apos;{0}&apos; must have value..
        /// </summary>
        public static string SentenceMissingGroupOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingGroupOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required option &apos;{0}&apos; is missing..
        /// </summary>
        public static string SentenceMissingRequiredOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required value not bound to option name is missing..
        /// </summary>
        public static string SentenceMissingRequiredValueError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; has no value..
        /// </summary>
        public static string SentenceMissingValueOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingValueOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options: {0} are not compatible with {1}..
        /// </summary>
        public static string SentenceMutuallyExclusiveSetErrors {
            get {
                return ResourceManager.GetString("SentenceMutuallyExclusiveSetErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verb selected..
        /// </summary>
        public static string SentenceNoVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceNoVerbSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is defined multiple times..
        /// </summary>
        public static string SentenceRepeatedOptionError {
            get {
                return ResourceManager.GetString("SentenceRepeatedOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required..
        /// </summary>
        public static string SentenceRequiredWord {
            get {
                return ResourceManager.GetString("SentenceRequiredWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence option &apos;{0}&apos; is defined with fewer or more items than required..
        /// </summary>
        public static string SentenceSequenceOutOfRangeErrorOption {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sequence value not bound to option name is defined with few items than required..
        /// </summary>
        public static string SentenceSequenceOutOfRangeErrorValue {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error setting value to option &apos;{0}&apos;: {1}.
        /// </summary>
        public static string SentenceSetValueExceptionError {
            get {
                return ResourceManager.GetString("SentenceSetValueExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option &apos;{0}&apos; is unknown..
        /// </summary>
        public static string SentenceUnknownOptionError {
            get {
                return ResourceManager.GetString("SentenceUnknownOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USAGE:.
        /// </summary>
        public static string SentenceUsageHeadingText {
            get {
                return ResourceManager.GetString("SentenceUsageHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display version information..
        /// </summary>
        public static string SentenceVersionCommandText {
            get {
                return ResourceManager.GetString("SentenceVersionCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download plugin {0} successfully..
        /// </summary>
        public static string SuccessDownloadPlugin {
            get {
                return ResourceManager.GetString("SuccessDownloadPlugin", resourceCulture);
            }
        }
    }
}
