//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AVOne.Tool.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AVOne.Tool.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Directory is null or not exist. 的本地化字符串。
        /// </summary>
        public static string ErrorDir {
            get {
                return ResourceManager.GetString("ErrorDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Directory &apos;{}&apos; not exists. 的本地化字符串。
        /// </summary>
        public static string ErrorDirectoryNotExists {
            get {
                return ResourceManager.GetString("ErrorDirectoryNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File path &apos;{0}&apos; not exists. 的本地化字符串。
        /// </summary>
        public static string ErrorPathNotExists {
            get {
                return ResourceManager.GetString("ErrorPathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 normal scenario 的本地化字符串。
        /// </summary>
        public static string ExamplesNormalScenario {
            get {
                return ResourceManager.GetString("ExamplesNormalScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Collection Type, could be PornMovie,default is PornMovie. 的本地化字符串。
        /// </summary>
        public static string HelpTextCollectionType {
            get {
                return ResourceManager.GetString("HelpTextCollectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path to use for the data folder (database files, etc.). 的本地化字符串。
        /// </summary>
        public static string HelpTextdatadir {
            get {
                return ResourceManager.GetString("HelpTextdatadir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path to scan. 的本地化字符串。
        /// </summary>
        public static string HelpTextDirectory {
            get {
                return ResourceManager.GetString("HelpTextDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Path to external FFmpeg executable to use in place of default found in PATH. 的本地化字符串。
        /// </summary>
        public static string HelpTextffmpeg {
            get {
                return ResourceManager.GetString("HelpTextffmpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 filename 的本地化字符串。
        /// </summary>
        public static string HelpTextFileName {
            get {
                return ResourceManager.GetString("HelpTextFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan &amp; organize files under specific folder.  的本地化字符串。
        /// </summary>
        public static string HelpTextVerbOrganize {
            get {
                return ResourceManager.GetString("HelpTextVerbOrganize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Print movie metadata by filename. 的本地化字符串。
        /// </summary>
        public static string HelpTextVerbPrintMetadata {
            get {
                return ResourceManager.GetString("HelpTextVerbPrintMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Scan files under specific folder and preview the organize result. 的本地化字符串。
        /// </summary>
        public static string HelpTextVerbScan {
            get {
                return ResourceManager.GetString("HelpTextVerbScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File path &apos;{0}&apos; not valid media file. 的本地化字符串。
        /// </summary>
        public static string InvalidMoviePath {
            get {
                return ResourceManager.GetString("InvalidMoviePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Možnost &apos;{0}&apos; je definována ve špatném formátu. 的本地化字符串。
        /// </summary>
        public static string SentenceBadFormatConversionErrorOption {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A value not bound to option name is defined with a bad format. 的本地化字符串。
        /// </summary>
        public static string SentenceBadFormatConversionErrorValue {
            get {
                return ResourceManager.GetString("SentenceBadFormatConversionErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Token &apos;{0}&apos; is not recognized. 的本地化字符串。
        /// </summary>
        public static string SentenceBadFormatTokenError {
            get {
                return ResourceManager.GetString("SentenceBadFormatTokenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Verb &apos;{0}&apos; is not recognized. 的本地化字符串。
        /// </summary>
        public static string SentenceBadVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceBadVerbSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误(S): 的本地化字符串。
        /// </summary>
        public static string SentenceErrorsHeadingText {
            get {
                return ResourceManager.GetString("SentenceErrorsHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display this help screen. 的本地化字符串。
        /// </summary>
        public static string SentenceHelpCommandTextOption {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display more information on a specific command. 的本地化字符串。
        /// </summary>
        public static string SentenceHelpCommandTextVerb {
            get {
                return ResourceManager.GetString("SentenceHelpCommandTextVerb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required option &apos;{0}&apos; is missing. 的本地化字符串。
        /// </summary>
        public static string SentenceMissingRequiredOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A required value not bound to option name is missing. 的本地化字符串。
        /// </summary>
        public static string SentenceMissingRequiredValueError {
            get {
                return ResourceManager.GetString("SentenceMissingRequiredValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option &apos;{0}&apos; has no value. 的本地化字符串。
        /// </summary>
        public static string SentenceMissingValueOptionError {
            get {
                return ResourceManager.GetString("SentenceMissingValueOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Options: {0} are not compatible with {1}. 的本地化字符串。
        /// </summary>
        public static string SentenceMutuallyExclusiveSetErrors {
            get {
                return ResourceManager.GetString("SentenceMutuallyExclusiveSetErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No verb selected. 的本地化字符串。
        /// </summary>
        public static string SentenceNoVerbSelectedError {
            get {
                return ResourceManager.GetString("SentenceNoVerbSelectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option &apos;{0}&apos; is defined multiple times. 的本地化字符串。
        /// </summary>
        public static string SentenceRepeatedOptionError {
            get {
                return ResourceManager.GetString("SentenceRepeatedOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Required. 的本地化字符串。
        /// </summary>
        public static string SentenceRequiredWord {
            get {
                return ResourceManager.GetString("SentenceRequiredWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A sequence option &apos;{0}&apos; is defined with fewer or more items than required. 的本地化字符串。
        /// </summary>
        public static string SentenceSequenceOutOfRangeErrorOption {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A sequence value not bound to option name is defined with few items than required. 的本地化字符串。
        /// </summary>
        public static string SentenceSequenceOutOfRangeErrorValue {
            get {
                return ResourceManager.GetString("SentenceSequenceOutOfRangeErrorValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error setting value to option &apos;{0}&apos;: {1} 的本地化字符串。
        /// </summary>
        public static string SentenceSetValueExceptionError {
            get {
                return ResourceManager.GetString("SentenceSetValueExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Option &apos;{0}&apos; is unknown. 的本地化字符串。
        /// </summary>
        public static string SentenceUnknownOptionError {
            get {
                return ResourceManager.GetString("SentenceUnknownOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USAGE: 的本地化字符串。
        /// </summary>
        public static string SentenceUsageHeadingText {
            get {
                return ResourceManager.GetString("SentenceUsageHeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Display version information. 的本地化字符串。
        /// </summary>
        public static string SentenceVersionCommandText {
            get {
                return ResourceManager.GetString("SentenceVersionCommandText", resourceCulture);
            }
        }
    }
}
